type ActivityLog {
  id: String!
  actionDescription: String
	action: String
	objectId: String
	objectType: String
  payload: JSON
  lastData: JSON
	creatorId: String
	# references: [ActivityReference]
  createdAt: Date

  # resolver
  creator: User
  jobApplicant: JobApplicant
}

enum ActivityOrder {
  action_DESC
  action_ASC
  createdAt_DESC
  createdAt_ASC
}

input ActivityFilter {
  OR: [ActivityFilter!]
  AND: [ActivityFilter!]
  action_regex: String
  actionDescription_regex: String
  objectType: String
  createdAt_between: [Date]
}

type ActivityReference {
  objectId: String
	objectType: String
}

type CreateActivityResponse {
  success: Boolean!
  message: String
  activity: ActivityLog
}

type UpdateActivityResponse {
  success: Boolean!
  message: String
  activity: ActivityLog
}

type DeleteActivityResponse {
  success: Boolean!
  message: String
}

input ActivityLogInput {
  actionDescription: String
  action: String
  objectId: String
  objectType: String
  creatorId: String
  payload: JSON
  lastData: JSON
}

input ActivityReferenceInput {
  objectId: String
	objectType: String
}

input ActivityObject {
  actionDescription: String
  action: String
  objectId: String
  objectType: String
  creatorId: String
  # references: [ActivityReferenceInput]
}

type Query {
  allActivities(filter: ActivityFilter, first: Int, skip: Int, orderBy: ActivityOrder): [ActivityLog]
  _allActivitiesMeta(filter: ActivityFilter, first: Int, skip: Int): ObjectMeta
  allActivityLogs(filter: ActivityFilter, first: Int, skip: Int, orderBy: ActivityOrder): [ActivityLog]
  _allActivityLogsMeta(filter: ActivityFilter, first: Int, skip: Int): ObjectMeta
  allJobApplicantActivities(filter: ActivityFilter, jobApplicantFilter: JobApplicantFilter, first: Int, skip: Int, orderBy: ActivityOrder): [ActivityLog]
  getActivity(id: String): ActivityLog
  getActivityLog(id: String): ActivityLog
}

type Mutation {
  createActivityLog(
    input: ActivityLogInput
    actionDescription: String
    action: String
    objectId: String
    objectType: String
    creatorId: String
    payload: JSON
    lastData: JSON
  ): CreateActivityResponse
  createActivityLogs(activities: [ActivityObject!]!): [ActivityLog!]!
  updateActivityLog(
    id: String!
    input: ActivityLogInput
    actionDescription: String
    action: String
    objectId: String
    objectType: String
    creatorId: String
    payload: JSON
    lastData: JSON
  ): UpdateActivityResponse
  deleteActivityLog(id: String!): DeleteActivityResponse
}

type ActivityLogSubscriptionPayload {
  mutation: _ModelMutationType!
  node: ActivityLog
  previousValues: ActivityLog
}

type Subscription {
  ActivityLog(filter: SubscriptionFilter, dataFilter: ActivityFilter): ActivityLogSubscriptionPayload
}